### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by qiujian16**

### CODE REVIEW

**Comment by qiujian16** [comment]
I removed the origin arch diagram and grc part, since according to the feedback. We should put open source part only  at first, and update this when more components are open sourced.

FYI @juliana-hsu @mikeshng

**Comment by juliana-hsu** [comment]
Some rewording recommendations for the main readme:  
open-cluster-management uses a hub - agents model. A hub centralizes control.  Agents (which we call klusterlet) reside in each cluster to manage registration to the hub and execute hub instructions.

API and controller for cluster registration and manifests delivery to clusters.  Simple core functions to connect clusters (klusterlet) to the hub.  Other components run upon this base. The following repositories describe the API and controllers for registration.

There are demonstrations available here:  https://github.com/open-cluster-management/demo-subscription-gitops .

**Comment by juliana-hsu** [comment]
About the api section:
The api repository defines relevant concepts and types for problem domains related to managing 0..* Kubernetes clusters.
- Is the 0..* a typo? Or should we say various?

**Comment by juliana-hsu** [comment]
Contributing section:
Now, you can follow the getting started guide to work with the xxx.
- What is xxx?

**Comment by juliana-hsu** [comment]
development.md section (some typos):
Generating a CRD for the first time
Make sure you have controller-gen locally installed in the _output/tools/bin directory.
For example, addon APIs are in the ./addon/v1alpha1 directory.
and you can simply remove these two lines: 
in _calls to the Makefile targets._

**Comment by juliana-hsu** [comment]
operators-subscription section:
Find the nginx pods deployed to current namespace, and the number of backend pods is overwritten to 3
- Apparently looking at the dictionary definition, overwritten is to replace completely and overridden is to replace for some cases (learn something new every day).  Which is applicable here?

Troubleshooting

Please refer to Troubleshooting documentation for further info.

If you have any further questions, please refer to help documentation for further information.
- the help documentation link seems to be missing?

**Comment by juliana-hsu** [comment]
operators-deployable readme is missing?

**Comment by juliana-hsu** [comment]
operators-placementrule readme is missing?

**Comment by juliana-hsu** [comment]
operators-channel section:

Channel controller syncs and promotes resources from the target source to a channel namespace on your hub cluster or to a host(such as object bucket). Then your subscription can consume these resources from the channel directly.

Examples can be found under the examples folder.

For a quick start, we are going to create a namespace channel, meaning you can add the resource to a namespace, which is watched by our channel operator, then the operator will promote this resource to the namespace channel, which should be the namespace where the channel operator sits.

The following example is tested on a minikube, so that you can play with this operator without worrying about things such as security.

Setting up a channel to sync resources between your hub cluster and an object bucket

Create a channel and deploy the payload (the resource you want the channel operator to help you move/promote)

The result, a config map wrapped by deployable in the default namespace.  It will also deploy a channel resource in the ch-ns namespace.

The resource is moved to its destination, and subscription can take over from here, deploying this resource (it will be the ConfigMap deployed) to your managed cluster.
- singular resource?

Troubleshooting

Normally we check the reconcile trace. For each flow, it should at least have a valid reconcile log for the deployable.

Please refer to Troubleshooting documentation for further info.

**Comment by juliana-hsu** [comment]
operators-subscription section:

Subscribes resources from channels and applies them to kubernetes

Find the nginx pods deployed to current namespace, and the number of backend pods overwritten to 3
- see previous comment about same sentence

Troubleshooting

Please refer to Troubleshooting documentation for further info.

**Comment by qiujian16** [comment]
@juliana-hsu you could directly add comments on each line of code, that would make it easier to understand :)

**Comment by juliana-hsu** [comment]
Where is the Contributor License Agreement mentioned in the Contributing a Patch section?  Should I reach out to legal to get one?   
Update from legal:  
We don't use CLAs at Red Hat as a matter of policy.
We do recommend that projects use the DCO (Developer Certificate of
Origin) and we have adopted a somewhat relaxed view of how that can be
implemented.

Richard

Juliana:  I'll do research on what this means.

**Comment by juliana-hsu** [comment]
Some comments on the policy collection community.  The DCO needs to be added to the CONTRIBUTING Doc.  Small typo (italicized):  "Resources: View the following resources for more information on the components and mechanisms _that_ are implemented in the product governance framework."  
Need to put on the website a rough timeline for the availability of GRC.

**Review by cadawson — CHANGES_REQUESTED** [review]
Do we need installation information? 
I am guessing that CHARTER.md will be added after the community gets together and agrees to one. Is that correct?
Do we need a start to an OWNERS.md files?

**Comment by qiujian16** [comment]
@cadawson thanks would  you like to add comment by lines?

**Comment by qiujian16** [comment]
@cadawson would you like to review  this again?

**Pull request merged**
