### PR TITLE
Fix community meeting URL

### PR DESCRIPTION
**Pull request by chenz4027**
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/114

Signed-off-by: Maggie Chen <magchen@redhat.com>

### CODE REVIEW

**Review by mikeshng — COMMENTED** [review]
Sorry what's wrong with the current url ?
https://github.com/open-cluster-management-io/community#community-meetings

It seems to be fine as it redirects to content

```
Community meetings
The community meets on a bi-weekly cadence on Thursday at 15:30 UTC.

Meeting Agenda and Topics can be found here: https://github.com/open-cluster-management-io/community/projects/1.

Meeting dial-in details, meeting notes and agendas are announced and published to the open-cluster-management mailing list on Google Groups.
```

**Comment by chenz4027** [comment]
@mikeshng Okay I think the way it was structured raised some confusions. All the links except the `Community meetings` directs the user to connect to each platform directly while `Community meetings` actual refer to the session. However, given this page is not long enough and Community meetings section is the second last section of readme, the user would think that the link doesn't work, which was reported in https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/114 - see the following recording for how it looks like. 

https://user-images.githubusercontent.com/26282541/124964710-5586af80-dfef-11eb-9a3f-92132325e2a2.mov
image

**Review by mikeshng — APPROVED** [review]
/lgtm

Thanks for the explanation and the fix!

**Comment by mikeshng** [comment]
@chenz4027 you will need to fix your commit by 
`git commit -s --amend` then `git push -f blahblahblah`

As to fix your git -s I think there is a global git config setting where you can set your name and email.

**Comment by chenz4027** [comment]
@mikeshng Seems like it needs an approval to run workflows as new changes are in

**Pull request merged**
